import { geistSans, geistMono, poppins } from "./fonts/fonts";
import "./globals.css";
import { Providers } from "./providers";
import { dehydrate, QueryClient } from "@tanstack/react-query";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient();

const dehydratedState = dehydrate(queryClient);

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} antialiased`}>
        <Providers state={dehydratedState}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
